version: '3.4'

networks:
  eshop-dev:
    driver: bridge
services:
  catalog-service:
    container_name: catalog_service
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=../https/catalog_service.pfx
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - eshop-dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./CatalogService/certs:/https
  mongo-db:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: eshop_user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - eshop-dev
    volumes:
      - mongo-data:/var/lib/mongo/data
volumes:
  mongo-data: 
