version: '3.4'

networks:
  eshop-dev:
    driver: bridge

volumes:
  mongo-data: 

services:
#Front
  frontend-app:
    container_name: frontend_react
    build:
      context: ./eshop_react_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

#Catalog-service
  catalog-service:
    container_name: catalog_service
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=../https/catalog_service.pfx
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - eshop-dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./CatalogService/certs:/https

#Mongo
  mongo-db:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: eshop_user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - eshop-dev
    volumes:
      - mongo-data:/var/lib/mongo/data

#Nginx
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    container_name: nginx
    image: 
    ports:
      - "80"
      - "443"

